Validate Exposed and Global extended attributes
w3c/webref pull request #492
Opened 2022-02-04 10:50 UTC by foolip

This test will catch situations like this one:
https://github.com/w3c/webrtc-identity/pull/36

2022-02-04 10:50 UTC, foolip commented
I've confirmed that this test failed before e95adca52e22ab9e57ffcee582c4423a0cca44e4.

2022-02-04 15:18 UTC, tidoust requested changes
Thanks! That looks good, I just suggest a few tweaks to give a more useful failure message than "expected true, got false" when test fails.

2022-02-04 15:18 UTC, tidoust commented on test/idl/consistency.js
> +    it('Exposed and Global extended attributes', function () {
```suggestion
    it('contains consistent Exposed and Global extended attributes', function () {
```

2022-02-04 15:18 UTC, tidoust commented on test/idl/consistency.js
> +        assert(Array.isArray(ids));
```suggestion
        assert(Array.isArray(ids), `Unexpected Global attribute value on ${dfn.name}: ${ids}`);
```

2022-02-04 15:18 UTC, tidoust commented on test/idl/consistency.js
> +      assert(globals.has('Window'));
```suggestion
      assert(globals.has('Window'), 'List of known globals does not include "Window"');
```

2022-02-04 15:18 UTC, tidoust commented on test/idl/consistency.js
> +      assert(globals.has('ServiceWorker'));
```suggestion
      assert(globals.has('ServiceWorker'), 'List of known globals does not include "ServiceWorker"');
```

2022-02-04 15:18 UTC, tidoust commented on test/idl/consistency.js
> +            assert(globals.has(id), ``);
```suggestion
            assert(globals.has(id), `Exposed attribute value ${id} on ${dfn.name} does not match any known global name`);
```

2022-02-04 15:18 UTC, tidoust commented on test/idl/consistency.js
> +                assert(globals.has(id));
```suggestion
                assert(globals.has(id), `Exposed attribute value ${id} on ${dfn.name}.${member.name} does not match any known global name`);
```

2022-02-04 15:18 UTC, tidoust commented on test/idl/consistency.js
> +            throw new Error(`Unexpected RHS for extended attribute ${name} on ${node.name}`);
```suggestion
            throw new Error(`Unexpected RHS for extended attribute ${name} on ${node.name}: ${attr.rhs?.type}`);
```

2022-02-04 15:18 UTC, tidoust commented on test/idl/consistency.js
> +            console.log(attr.rhs.type)
```suggestion
```

2022-02-09 10:08 UTC, tidoust commented
Comments being editorial, I'll integrate them and merge.

2022-02-09 10:09 UTC, tidoust approved these changes

2022-02-09 10:12 UTC, merged

2022-02-09 11:19 UTC, foolip commented
Thanks @tidoust!